class Equippable:
    def __init__(self, slot, power_bonus=0, defense_bonus=0, max_hp_bonus=0,
                    blank_power_bonus=0, blank_defense_bonus=0, max_blank_element_bonus=0,
                    fire_power_bonus=0, fire_defense_bonus=0, max_fire_element_bonus=0,
                    air_power_bonus=0, air_defense_bonus=0, max_air_element_bonus=0,
                    ice_power_bonus=0, ice_defense_bonus=0, max_ice_element_bonus=0,
                    lightning_power_bonus=0, lightning_defense_bonus=0, max_lightning_element_bonus=0,
                    earth_power_bonus=0, earth_defense_bonus=0, max_earth_element_bonus=0,
                    psychic_power_bonus=0, psychic_defense_bonus=0, max_psychic_element_bonus=0,
                    water_power_bonus=0, water_defense_bonus=0, max_water_element_bonus=0):
        self.slot = slot
        self.power_bonus = power_bonus
        self.defense_bonus = defense_bonus
        self.max_hp_bonus = max_hp_bonus
        self.blank_power_bonus = blank_power_bonus
        self.blank_defense_bonus = blank_defense_bonus
        self.fire_power_bonus = fire_power_bonus
        self.fire_defense_bonus = fire_defense_bonus
        self.air_power_bonus = air_power_bonus
        self.air_defense_bonus = air_defense_bonus
        self.ice_power_bonus = ice_power_bonus
        self.ice_defense_bonus = ice_defense_bonus
        self.lightning_power_bonus = lightning_power_bonus
        self.lightning_defense_bonus = lightning_defense_bonus
        self.earth_power_bonus = earth_power_bonus
        self.earth_defense_bonus = earth_defense_bonus
        self.psychic_power_bonus = psychic_power_bonus
        self.psychic_defense_bonus = psychic_defense_bonus
        self.water_power_bonus = water_power_bonus
        self.water_defense_bonus = water_defense_bonus
        
        self.max_blank_element_bonus = max_blank_element_bonus
        self.max_fire_element_bonus = max_fire_element_bonus
        self.max_air_element_bonus = max_air_element_bonus
        self.max_ice_element_bonus = max_ice_element_bonus
        self.max_lightning_element_bonus = max_lightning_element_bonus
        self.max_earth_element_bonus = max_earth_element_bonus
        self.max_psychic_element_bonus = max_psychic_element_bonus
        self.max_water_element_bonus = max_water_element_bonus